Repository una-ui/una-ui, pull requests merged in 2024-09, with the labels that each got.

#200 fix(types): Generate nuxt types automatically at install
  .github/workflows/ci.yml
  packages/nuxt/build.config.ts
  packages/nuxt/package.json
  packages/nuxt/src/module.ts
  packages/nuxt/src/runtime/components/elements/Link.vue
  packages/nuxt/src/runtime/components/misc/ThemeSwitcher.vue
  packages/nuxt/src/runtime/composables/useUnaSettings.ts
  packages/nuxt/src/runtime/plugins/theme.client.ts
  packages/nuxt/src/runtime/plugins/theme.server.ts
  packages/nuxt/tsconfig.json
  tsconfig.json
Labels: c: bug 🐞

#204 chore: relock dependencies
  pnpm-lock.yaml
Labels: c: chore 🌳, c: dependencies 📦, c: performance 🏄‍♂️

#208 feat(preset): add area-* shortcut as an alternative to tailwind size-*
  packages/preset/src/_shortcuts/general.ts
Labels: c: preset ✨

#216 fix(Accordion): reconfig trigger button height style
  packages/nuxt/src/runtime/components/elements/Accordion.vue
Labels: c: bug 🐞, c: component 🏝️

#248 refactor(Switch)!: reimplement `props` and `presets` with radix-vue
  docs/components/content/examples/vue/switch/ExampleVueSwitchBasic.vue
  docs/components/content/examples/vue/switch/ExampleVueSwitchColor.vue
  docs/components/content/examples/vue/switch/ExampleVueSwitchCustom.vue
  docs/components/content/examples/vue/switch/ExampleVueSwitchDisabled.vue
  docs/components/content/examples/vue/switch/ExampleVueSwitchFocus.vue
  docs/components/content/examples/vue/switch/ExampleVueSwitchIcon.vue
  docs/components/content/examples/vue/switch/ExampleVueSwitchLabel.vue
  docs/components/content/examples/vue/switch/ExampleVueSwitchLoading.vue
  docs/components/content/examples/vue/switch/ExampleVueSwitchOutset.vue
  docs/components/content/examples/vue/switch/ExampleVueSwitchSize.vue
  docs/content/3.components/switch.md
  packages/nuxt/playground/app.vue
  packages/nuxt/playground/components/Switch.vue
  packages/nuxt/src/runtime/components/forms/Switch.vue
  packages/nuxt/src/runtime/types/switch.ts
  packages/preset/src/_shortcuts/switch.ts
  packages/preset/src/prefixes.ts
  scripts/prepare.ts
Labels: c: refactor, c: component 🏝️

#196 feat(Dialog): Implement new component and preset
  .vscode/settings.json
  docs/components/content/examples/vue/dialog/ExampleVueDialogBackgroundBlur.vue
  docs/components/content/examples/vue/dialog/ExampleVueDialogBasic.vue
  docs/components/content/examples/vue/dialog/ExampleVueDialogConfirmation.vue
  docs/components/content/examples/vue/dialog/ExampleVueDialogCustomClose.vue
  docs/components/content/examples/vue/dialog/ExampleVueDialogLoading.vue
  docs/components/content/examples/vue/dialog/ExampleVueDialogLogin.vue
  docs/components/content/examples/vue/dialog/ExampleVueDialogPreventClose.vue
  docs/components/content/examples/vue/dialog/ExampleVueDialogScrollable.vue
  docs/components/content/examples/vue/dialog/ExampleVueDialogScrollableBody.vue
  docs/content/3.components/dialog.md
  docs/content/3.components/dropdown-menu.md
  packages/nuxt/playground/app.vue
  packages/nuxt/playground/components/Dialog.vue
  packages/nuxt/playground/components/Switch.vue
  packages/nuxt/src/module.ts
  packages/nuxt/src/runtime/components/elements/dialog/Dialog.vue
  packages/nuxt/src/runtime/components/elements/dialog/DialogClose.vue
  packages/nuxt/src/runtime/components/elements/dialog/DialogContent.vue
  packages/nuxt/src/runtime/components/elements/dialog/DialogDescription.vue
  packages/nuxt/src/runtime/components/elements/dialog/DialogFooter.vue
  packages/nuxt/src/runtime/components/elements/dialog/DialogHeader.vue
  packages/nuxt/src/runtime/components/elements/dialog/DialogOverlay.vue
  packages/nuxt/src/runtime/components/elements/dialog/DialogScrollContent.vue
  packages/nuxt/src/runtime/components/elements/dialog/DialogTitle.vue
  packages/nuxt/src/runtime/types/dialog.ts
  packages/nuxt/src/runtime/types/index.ts
  packages/preset/src/_shortcuts/btn.ts
  packages/preset/src/_shortcuts/dialog.ts
  packages/preset/src/_shortcuts/index.ts
  packages/preset/src/_shortcuts/popover.ts
  packages/preset/src/prefixes.ts
  uno.config.ts
Labels: c: feature 🚀, c: component 🏝️, c: preset ✨
