Repository una-ui/una-ui, pull requests merged in 2024-08, with the labels that each got.

#151 feat(Separator): introduce new component and preset
  docs/components/content/examples/vue/divider/ExampleVueDividerAlignments.vue
  docs/components/content/examples/vue/divider/ExampleVueDividerBasic.vue
  docs/components/content/examples/vue/divider/ExampleVueDividerColor.vue
  docs/components/content/examples/vue/divider/ExampleVueDividerType.vue
  docs/components/content/examples/vue/divider/ExampleVueDividerVariant.vue
  docs/components/content/examples/vue/separator/ExampleVueSeparatorBasic.vue
  docs/components/content/examples/vue/separator/ExampleVueSeparatorColor.vue
  docs/components/content/examples/vue/separator/ExampleVueSeparatorOrientation.vue
  docs/components/content/examples/vue/separator/ExampleVueSeparatorPosition.vue
  docs/components/content/examples/vue/separator/ExampleVueSeparatorSize.vue
  docs/components/content/examples/vue/separator/ExampleVueSeparatorVariant.vue
  docs/content/3.components/separator.md
  packages/nuxt/playground/app.vue
  packages/nuxt/playground/components/Divider.vue
  packages/nuxt/playground/components/Separator.vue
  packages/nuxt/src/runtime/components/elements/Divider.vue
  packages/nuxt/src/runtime/components/elements/Separator.vue
  packages/nuxt/src/runtime/types/divider.ts
  packages/nuxt/src/runtime/types/index.ts
  packages/nuxt/src/runtime/types/separator.ts
  packages/preset/src/_shortcuts/divider.ts
  packages/preset/src/_shortcuts/index.ts
  packages/preset/src/_shortcuts/separator.ts
  packages/preset/src/prefixes.ts
  pnpm-lock.yaml
  uno.config.ts
Labels: s: needs decision

#152 feat(Tabs): introduce new component and preset
  docs/components/content/examples/vue/tabs/ExampleVueTabsBasic.vue
  docs/components/content/examples/vue/tabs/ExampleVueTabsColor.vue
  docs/components/content/examples/vue/tabs/ExampleVueTabsDisabled.vue
  docs/components/content/examples/vue/tabs/ExampleVueTabsSize.vue
  docs/content/3.components/tabs.md
  packages/nuxt/playground/app.vue
  packages/nuxt/playground/components/Tabs.vue
  packages/nuxt/src/module.ts
  packages/nuxt/src/runtime/components/elements/tabs/Tabs.vue
  packages/nuxt/src/runtime/components/elements/tabs/TabsContent.vue
  packages/nuxt/src/runtime/components/elements/tabs/TabsList.vue
  packages/nuxt/src/runtime/components/elements/tabs/TabsRoot.vue
  packages/nuxt/src/runtime/components/elements/tabs/TabsTrigger.vue
  packages/nuxt/src/runtime/types/index.ts
  packages/nuxt/src/runtime/types/tabs.ts
  packages/preset/src/_shortcuts/index.ts
  packages/preset/src/_shortcuts/tabs.ts
  packages/preset/src/prefixes.ts
  pnpm-lock.yaml
  uno.config.ts
Labels: c: component 🏝️, c: preset ✨

#157 feat(Table): WIP
  docs/components/content/examples/vue/table/ExampleVueTableBasic.vue
  docs/components/content/examples/vue/table/ExampleVueTableColumnFiltering.vue
  docs/components/content/examples/vue/table/ExampleVueTableColumnOrdering.vue
  docs/components/content/examples/vue/table/ExampleVueTableColumnPinning.vue
  docs/components/content/examples/vue/table/ExampleVueTableExpanding.vue
  docs/components/content/examples/vue/table/ExampleVueTableGlobalFiltering.vue
  docs/components/content/examples/vue/table/ExampleVueTableGrouping.vue
  docs/components/content/examples/vue/table/ExampleVueTableLoading.vue
  docs/components/content/examples/vue/table/ExampleVueTablePagination.vue
  docs/components/content/examples/vue/table/ExampleVueTableRowSelection.vue
  docs/components/content/examples/vue/table/ExampleVueTableServerSide.vue
  docs/components/content/examples/vue/table/ExampleVueTableSlots.vue
  docs/components/content/examples/vue/table/ExampleVueTableSorting.vue
  docs/components/content/examples/vue/table/ExampleVueTableVisibility.vue
  docs/components/content/examples/vue/table/makeData.ts
  docs/components/content/examples/vue/tabs/ExampleVueTabsBasic.vue
  docs/components/content/examples/vue/tabs/ExampleVueTabsColor.vue
  docs/content/3.components/table.md
  docs/package.json
  package.json
  packages/nuxt/README.md
  packages/nuxt/package.json
  packages/nuxt/playground/app.vue
  packages/nuxt/playground/components/Table.vue
  packages/nuxt/src/module.ts
  packages/nuxt/src/runtime/components/data/table/Table.vue
  packages/nuxt/src/runtime/components/data/table/TableBody.vue
  packages/nuxt/src/runtime/components/data/table/TableCaption.vue
  packages/nuxt/src/runtime/components/data/table/TableCell.vue
  packages/nuxt/src/runtime/components/data/table/TableEmpty.vue
  packages/nuxt/src/runtime/components/data/table/TableFooter.vue
  packages/nuxt/src/runtime/components/data/table/TableHead.vue
  packages/nuxt/src/runtime/components/data/table/TableHeader.vue
  packages/nuxt/src/runtime/components/data/table/TableLoading.vue
  packages/nuxt/src/runtime/components/data/table/TableRoot.vue
  packages/nuxt/src/runtime/components/data/table/TableRow.vue
  packages/nuxt/src/runtime/components/elements/Accordion.vue
  packages/nuxt/src/runtime/components/elements/Progress.vue
  packages/nuxt/src/runtime/components/forms/Checkbox.vue
  packages/nuxt/src/runtime/types/index.ts
  packages/nuxt/src/runtime/types/table.ts
  packages/nuxt/src/runtime/utils/cn.ts
  packages/preset/README.md
  packages/preset/src/_shortcuts/index.ts
  packages/preset/src/_shortcuts/table.ts
  packages/preset/src/prefixes.ts
  pnpm-lock.yaml
  uno.config.ts
Labels: s: on hold

#165 feat(Breadcrumb): introduce new component and preset
  docs/components/content/examples/vue/breadcrumb/ExampleVueBreadcrumbBasic.vue
  docs/components/content/examples/vue/breadcrumb/ExampleVueBreadcrumbSeparator.vue
  docs/components/content/examples/vue/breadcrumb/ExampleVueBreadcrumbSize.vue
  docs/components/content/examples/vue/breadcrumb/ExampleVueBreadcrumbSlots.vue
  docs/components/content/examples/vue/breadcrumb/ExampleVueBreadcrumbVariant.vue
  docs/content/3.components/breadcrumb.md
  packages/nuxt/playground/app.vue
  packages/nuxt/playground/components/Breadcrumb.vue
  packages/nuxt/playground/pages/index.vue
  packages/nuxt/playground/pages/test.vue
  packages/nuxt/playground/pages/test/index.vue
  packages/nuxt/playground/pages/test/test2.vue
  packages/nuxt/src/module.ts
  packages/nuxt/src/runtime/components/elements/Button.vue
  packages/nuxt/src/runtime/components/navigation/breadcrumb/Breadcrumb.vue
  packages/nuxt/src/runtime/components/navigation/breadcrumb/BreadcrumbEllipsis.vue
  packages/nuxt/src/runtime/components/navigation/breadcrumb/BreadcrumbItem.vue
  packages/nuxt/src/runtime/components/navigation/breadcrumb/BreadcrumbLink.vue
  packages/nuxt/src/runtime/components/navigation/breadcrumb/BreadcrumbList.vue
  packages/nuxt/src/runtime/components/navigation/breadcrumb/BreadcrumbRoot.vue
  packages/nuxt/src/runtime/components/navigation/breadcrumb/BreadcrumbSeparator.vue
  packages/nuxt/src/runtime/types/breadcrumb.ts
  packages/nuxt/src/runtime/types/button.ts
  packages/nuxt/src/runtime/types/index.ts
  packages/preset/src/_shortcuts/breadcrumb.ts
  packages/preset/src/_shortcuts/btn.ts
  packages/preset/src/_shortcuts/index.ts
  packages/preset/src/prefixes.ts
  scripts/prepare.ts
  uno.config.ts
Labels: s: on hold
